Enable cache golangci-lint result, go build and dependencies
reviewdog/action-golangci-lint pull request #75
Opened 2021-04-25 13:31 UTC by sawadashota

Enable cache of golangci-lint result, go-build and dependencies: like as `golangci/golangci-lint-action`.
https://github.com/golangci/golangci-lint-action/blob/7f1a4282b7343b30f26556118203f8c2751845d7/src/cache.ts#L26-L44

Cache enabled job is 1 minute faster than no cache in my environment. (1m22s -> 27s)

Without cache
![image](https://user-images.githubusercontent.com/21254456/115995270-95a3dc00-a615-11eb-9594-73cd93d47344.png)

Cache enabled
![image](https://user-images.githubusercontent.com/21254456/115995281-9dfc1700-a615-11eb-9849-a02483fcfffc.png)

2021-04-28 12:02 UTC, shogo82148 commented
Good suggestion!

But, a composite run steps action doesn't support `uses` steps.
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-run-steps-actions
Actually, the your action fails with the following errors.

https://github.com/reviewdog/action-golangci-lint/pull/75/checks?check_run_id=2457238725

```
Error: /home/runner/work/action-golangci-lint/action-golangci-lint/./action.yml (Line: 48, Col: 7): Unexpected value 'uses'
Error: /home/runner/work/action-golangci-lint/action-golangci-lint/./action.yml (Line: 49, Col: 7): Unexpected value 'with'
Error: /home/runner/work/action-golangci-lint/action-golangci-lint/./action.yml (Line: 48, Col: 7): Required property is missing: run
Error: /home/runner/work/action-golangci-lint/action-golangci-lint/./action.yml (Line: 48, Col: 7): Required property is missing: shell
Error: /home/runner/work/action-golangci-lint/action-golangci-lint/./action.yml (Line: 55, Col: 7): Unexpected value 'uses'
Error: /home/runner/work/action-golangci-lint/action-golangci-lint/./action.yml (Line: 56, Col: 7): Unexpected value 'if'
Error: /home/runner/work/action-golangci-lint/action-golangci-lint/./action.yml (Line: 57, Col: 7): Unexpected value 'with'
(snip)
```

2021-04-29 06:38 UTC, sawadashota commented
Hmm... It needs a lot of works to enable cache in this action from I expected...
For now, how about only documentation how to enable cache?

2021-04-29 07:22 UTC, shogo82148 requested changes
Sounds good!

However, there are some syntax error.
Please fix them.

2021-04-29 07:22 UTC, shogo82148 commented on README.md
> +        if: ${{ inputs.skip-build-cache == 'false' }}
the input context is not available here.
remove it please

2021-04-29 07:22 UTC, shogo82148 commented on README.md
> +        if: ${{ inputs.skip-pkg-cache == 'false' }}
remove it please

2021-04-29 07:22 UTC, shogo82148 commented on README.md
> +          ${{ runner.os }}-golangci-lint-
The indentation is wrong.
It should be the same level as `actions/checkout@v1`.

2021-04-29 07:22 UTC, shogo82148 commented on README.md
> +      uses: reviewdog/action-golangci-lint@v1
The indentation is wrong.
It should be the same level as `actions/cache@v2` steps.

2021-04-29 10:04 UTC, sawadashota commented
I'm sorry about my boring mistakes...
I've fixed those!

2021-04-29 15:14 UTC, shogo82148 approved these changes
LGTM
Thanks!

2021-04-29 15:15 UTC, merged

2021-04-29 15:16 UTC, review-dog commented
Hi, @sawadashota! We merged your PR to reviewdog! 🐶
Thank you for your contribution! ✨

**We just invited you to join the @reviewdog organization on GitHub.**
Accept the invite by visiting https://github.com/orgs/reviewdog/invitation.
By joining the team, you'll be a part of reviewdog community and can help the maintainance of reviewdog.

Thanks again!